### ISSUE TITLE
请问这个怎么部署呢

### ISSUE THREAD

**Issue by ilovchara** [superkingM/music#1]

**Comment by superkingM** [comment]
readme有写怎么部署，时间久远不知道这个网易云的接口还能不能用

**Comment by ilovchara** [comment]
不需要下载什么其他的组件吗，好像不行hhh

**Comment by superkingM** [comment]
> 不需要下载什么其他的组件吗，好像不行hhh

lnmp环境，php7.2+mysql5.7，把sql导入到数据库，PHP得拓展按照workman的官网来安装

**Comment by ilovchara** [comment]
好的我再试试

**Comment by ilovchara** [comment]
搞不太懂前端怎么配置，php server.php我已经启动了，需要配置nginx？

**Comment by superkingM** [comment]
> 搞不太懂前端怎么配置，php server.php我已经启动了，需要配置nginx？


Applications/Song/Web是前端文件夹，index.html只要这个页面能访问就行了，里面的js中ws_hostname 需要配置成你服务端地址，本机应该不需要修改

**Comment by ilovchara** [comment]
然后用nginx代理到服务器域名？我是用服务器来部署的，但是面板好像识别不出web中的index.html

**Comment by ilovchara** [comment]
连接成功了，但是就是放不了歌

**Comment by superkingM** [comment]
> 连接成功了，但是就是放不了歌

放不了歌应该接口失效了，这个项目我也是改的原来的项目来了，要是接口失效了查不到歌曲

**Comment by ilovchara** [comment]
那好吧
